/**
 * Provides utility functions.
 *
 * @module
 */

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

/**
 * 将普通字符串转换为契合Opaque<"string">类型要求的对象
 * 
 * @param str 需要转换的字符串
 * @returns 带有tag和value字段的对象，符合Opaque<"string">类型要求
 */
export function toOpaqueString(str: string): { tag: string, value: string } {
  return { tag: "string", value: str };
}
